<a href="https://colab.research.google.com/github/Lee-Sang-A/AI-Programming/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%204%EC%A3%BC%EC%B0%A8%20%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 두번째 과제

import numpy as np

np.random.seed(85)

results = []

for _ in range(3):
    a = np.arange(1, 46)
    np.random.shuffle(a)
    lotto = a[:6]
    results.append(lotto)

lotto_array = np.array(results)

print('lotto_array =\n', lotto_array)

lotto_array =
 [[22  9 15 44 39 37]
 [ 7 31 24 40 11 16]
 [ 8  3 23 40 38 32]]


In [2]:
# 세번째 과제

import numpy as np

# 1. shape가 (3, 3, 6)이고, 배열 원소가 0~20 사이의 정수값을 갖는 3차원 배열 생성
shape_3d = (3, 3, 6)
arr_3d = np.random.randint(0, 21, shape_3d)
print("3차원 배열:\n", arr_3d)

# 2. shape가 (5, 6)이고, 배열 원소가 0~100 사이의 정수값을 갖는 2차원 배열 생성
shape_2d = (5, 6)
arr_2d = np.random.randint(0, 101, shape_2d)
print("2차원 배열:\n", arr_2d)

3차원 배열:
 [[[15  5  1 12 19 12]
  [16  4 19 16 18 15]
  [ 5  3 11  1 20  9]]

 [[ 5 10  8  5  8 17]
  [ 4 17 14  2  0 18]
  [15 20 15  8  9  8]]

 [[ 0 11  6  4  8  3]
  [ 7  6 18  4  7  4]
  [13  3 20  3  1  8]]]
2차원 배열:
 [[51 41 43 88 80 72]
 [43 41 69 65 72 91]
 [89 89 26 13 59 24]
 [ 2 54 31 76 85 87]
 [46 25 48 95 24 50]]


In [3]:
# 네번째 과제

import numpy as np

temp = np.arange(48)

# 3차원 배열 (4, 3, 4)로 변형
arr_3d_reshaped = temp.reshape(4, 3, 4)
print("3차원 배열 (4, 3, 4):\n", arr_3d_reshaped)

# 2차원 배열 (6, 8)로 변형
arr_2d_reshaped = temp.reshape(6, 8)
print("2차원 배열 (6, 8):\n", arr_2d_reshaped)

3차원 배열 (4, 3, 4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2차원 배열 (6, 8):
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
